PRINTER = 'Walter'
AXIS = "Z"
COMMENT="Z2 mit RD 0.35"
FEEDRATE = 200
ITERATIONS = 300

DIRECTION = "+"

#SERIAL_PORT = 'COM7'
SERIAL_PORT = '/dev/serial/by-id/usb-MAHR_16EXu_MA4LOA8N-if00-port0'
LOCAL = False
DATA_DIR = 'data'

MAX_POS = 12.5
MIN_POS = 0
SAFETY_DISTANCE = .25
SUSPICIOUS_ERROR = .04
